"""modification du champ created_at de la table feedbacks

Revision ID: 0f7b84e8f19c
Revises: 2496c1e20369
Create Date: 2026-06-08 22:18:20.542133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f7b84e8f19c'
down_revision = '2496c1e20369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['user_id'], ['id'])

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.drop_column('create_at')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['sender_coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'])

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
