"""Ajout des tables pour le paiement

Revision ID: 697c3ca607b9
Revises: 7ab8b6654d5c
Create Date: 2026-06-29 21:11:38.974320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '697c3ca607b9'
down_revision = '7ab8b6654d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['user_id'], ['id'])

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forfait', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expire_forfait', sa.DateTime(), nullable=True))

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['sender_coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'abonnements', ['abonnement_id'], ['id'])

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.alter_column('poste',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('poste',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('expire_forfait')
        batch_op.drop_column('forfait')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('abonnements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
