"""Ajout des tables notifications et collaboration

Revision ID: bb20b6d2e88c
Revises: 3ea38b715fb9
Create Date: 2026-05-23 17:47:16.050213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb20b6d2e88c'
down_revision = '3ea38b715fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['sender_coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'])

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
