"""Ajout du champ email au coach principal

Revision ID: c0a5a7d208a0
Revises: bb20b6d2e88c
Create Date: 2026-05-26 16:07:23.663083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a5a7d208a0'
down_revision = 'bb20b6d2e88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        # On commente cette ligne car la colonne existe déjà en base
        # batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

               
        # Remplir la colonne email pour les enregistrements existants
        # Utilise le telephone comme valeur temporaire unique si email est vide
        # ou une valeur par défaut si telephone est aussi vide
        batch_op.execute("UPDATE coaches SET email = CONCAT(telephone, '@example.com') WHERE email IS NULL OR email = ''")
        # Si telephone peut être null ou non unique, une alternative serait:
        # batch_op.execute("UPDATE coaches SET email = CONCAT('coach_', id, '@example.com') WHERE email IS NULL OR email = ''")


        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['sender_coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'])

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
