"""modification du champ exercice pour selectionner plusieurs domaines par exercice

Revision ID: cb9c7708a47f
Revises: bd15517c16b1
Create Date: 2026-07-09 11:02:08.897388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb9c7708a47f'
down_revision = 'bd15517c16b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['user_id'], ['id'])

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domaines', sa.JSON(), nullable=True))
        batch_op.alter_column('domaine',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])
        batch_op.create_foreign_key(None, 'coaches', ['sender_coach_id'], ['id'])

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'seances', ['seance_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'abonnements', ['abonnement_id'], ['id'])
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('partages_planning', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'joueurs', ['joueur_id'], ['id'])
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'])

    with op.batch_alter_table('rapports_mensuels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coaches', ['coach_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rapports_mensuels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('planning_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('partages_planning', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planning_id')

    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('domaine',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('domaines')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('abonnements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
